---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
data:
  USERNAME: "Andrez Higuera"
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
data:
  API_KEY: YWRtaW4xMjM0  # admin1234 en base64 como API_KEY
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend-base-devops
spec:
  replicas: 2  # Ajustar el número de réplicas según sea necesario
  selector:
    matchLabels:
      app: backend-base-devops
  template:
    metadata:
      labels:
        app: backend-base-devops
    spec:
      containers:
      - name: backend-container
        image: localhost:8082/backend-base-devops:latest  # La imagen Docker desde Nexus
        ports:
        - containerPort: 3001
        env:
        - name: USERNAME
          valueFrom:
            configMapKeyRef:
              name: backend-configmap
              key: USERNAME
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: API_KEY
      imagePullSecrets:  # Referencia al Secret que creamos
      - name: nexus-regcred  # Nombre del Secret que permite la autenticación en Nexus
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend-base-devops
  ports:
    - protocol: TCP
      port: 80  # Puerto expuesto externamente
      targetPort: 3001  # Puerto donde escucha el contenedor
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: backend.base.devops
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: backend-service
            port:
              number: 80
